/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kis1;

/*
 * This is main class
 */
public class App {

    /**
     * This is the main method
     * 
     * @param args
     */
    public static void main(String[] args) {
        UI a = new UI();
    }
}
